
import { Home } from "Home.slint";
import { ToDo } from "todo.slint";
import { App1 } from "App1.slint";


export component App inherits Window {
    width: 320px;
    height: 480px;
    in-out property <int> counter: 0;
    in property <string> todo_name:"hello";
    in-out property <int> page_number:0;
    background: #ccc;
    if (page_number == 0):  Home { }
    if (page_number == 1):  App1 {
        counter: counter;
    }
    if (page_number == 2):  ToDo {
        todo_name: todo_name;
    }
}
